version: '3.9'

services:
  sensor-climate:
    image: python3.11.6-slim-bullseye_iot_smart_home:latest
    hostname: sensor-climate
    command: python -m iot_smart_home.devices.mqtt.sensors.climate
    env_file:
      - .env
    environment:
      IOT_SMART_HOME_MQTT_BROKER_HOST: node1.emqx.io
      IOT_SMART_HOME_MQTT_SENSOR_TOPIC: sensors/climate
    restart: always
  sensor-lamp:
    image: python3.11.6-slim-bullseye_iot_smart_home:latest
    hostname: sensor-lamp
    command: python -m iot_smart_home.devices.mqtt.sensors.lamp
    env_file:
      - .env
    environment:
      IOT_SMART_HOME_MQTT_BROKER_HOST: node1.emqx.io
      IOT_SMART_HOME_MQTT_SENSOR_TOPIC: sensors/lamp
    restart: always
  sensor-motion:
    image: python3.11.6-slim-bullseye_iot_smart_home:latest
    hostname: sensor-motion
    command: python -m iot_smart_home.devices.mqtt.sensors.motion
    env_file:
      - .env
    environment:
      IOT_SMART_HOME_MQTT_BROKER_HOST: node1.emqx.io
      IOT_SMART_HOME_MQTT_SENSOR_TOPIC: sensors/motion
    restart: always
  controller:
    image: python3.11.6-slim-bullseye_iot_smart_home:latest
    hostname: controller
    command: python -m iot_smart_home.devices.mqtt.controller
    env_file:
      - .env
    environment:
      IOT_SMART_HOME_MQTT_BROKER_HOST: node1.emqx.io
    restart: always
    ports:
      - "5000:5000"