version: '3.9'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    ports:
      - "8123:8123"
