version: '3.9'

services:
  climate-sensor:
    build: .
    hostname: climate-sensor
    command: python -m device.sensors.climate
    env_file:
      - .env
    environment:
      DEVICE_MQTT_BROKER_ADDRESS: emqx1
      DEVICE_NAME: climate-sensor
      DEVICE_FREQUENCY: 2
    networks:
      - default
      - iot_smart_home_emqx-bridge
  lamp-sensor:
    build: .
    hostname: lamp-sensor
    command: python -m device.sensors.lamp
    env_file:
      - .env
    environment:
      DEVICE_MQTT_BROKER_ADDRESS: emqx1
      DEVICE_NAME: lamp-sensor
      DEVICE_FREQUENCY: 2
    networks:
      - default
      - iot_smart_home_emqx-bridge
  motion-sensor:
    build: .
    hostname: motion-sensor
    command: python -m device.sensors.motion
    env_file:
      - .env
    environment:
      DEVICE_MQTT_BROKER_ADDRESS: emqx1
      DEVICE_NAME: motion-sensor
      DEVICE_FREQUENCY: 2
    networks:
      - default
      - iot_smart_home_emqx-bridge
networks:
  iot_smart_home_emqx-bridge:
    external: true
  default:
    driver: bridge