version: '3.9'

services:
  emqx1:
    image: emqx:5.1.6
    container_name: emqx1
    environment:
      - EMQX_NODE_NAME=emqx@node1.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      default:
        aliases:
          - node1.emqx.io
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx1_data:/opt/emqx/data
  emqx2:
    image: emqx:5.1.6
    container_name: emqx2
    environment:
      - EMQX_NODE_NAME=emqx@node2.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      default:
        aliases:
          - node2.emqx.io
    volumes:
      - emqx2_data:/opt/emqx/data
    depends_on:
      emqx1:
        condition: service_healthy
  mqtt-sensor-climate:
    image: python3.11.6-slim-bullseye_iot_smart_home:latest
    hostname: mqtt-sensor-climate
    command: python -m iot_smart_home.devices.mqtt.sensors.climate
    env_file:
      - .env
    environment:
      IOT_SMART_HOME_MQTT_BROKER_HOST: node1.emqx.io
      IOT_SMART_HOME_MQTT_SENSOR_TOPIC: sensors/climate
    restart: always
  mqtt-sensor-lamp:
    image: python3.11.6-slim-bullseye_iot_smart_home:latest
    hostname: mqtt-sensor-lamp
    command: python -m iot_smart_home.devices.mqtt.sensors.lamp
    env_file:
      - .env
    environment:
      IOT_SMART_HOME_MQTT_BROKER_HOST: node1.emqx.io
      IOT_SMART_HOME_MQTT_SENSOR_TOPIC: sensors/lamp
    restart: always
  mqtt-sensor-motion:
    image: python3.11.6-slim-bullseye_iot_smart_home:latest
    hostname: mqtt-sensor-motion
    command: python -m iot_smart_home.devices.mqtt.sensors.motion
    env_file:
      - .env
    environment:
      IOT_SMART_HOME_MQTT_BROKER_HOST: node1.emqx.io
      IOT_SMART_HOME_MQTT_SENSOR_TOPIC: sensors/motion
volumes:
  emqx1_data:
  emqx2_data: