[tool.poetry]
name = "iot-smart-home"
version = "0.1.0"
description = ""
authors = ["coolworld2049 <coolworld2049@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"
paho-mqtt = "^1.6.1"
pydantic = "^2.4.2"
pydantic-settings = "^2.0.3"
fastapi = "^0.104.1"
loguru = "^0.7.2"
uptime = "^3.0.1"


[tool.poetry.group.dev.dependencies]
black = "^23.10.1"


[tool.poetry.group.ha.dependencies]
homeassistant = "^2023.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
